var express 	= require('express'),
	app     	= express(),
	favicon 	= require('serve-favicon'),
	ibmbluemix 	= require('ibmbluemix'),
	config  	= {
		// change to real application route assigned for your application
		applicationRoute : 'saucedb.mybluemix.net',
		// change to real application ID generated by Bluemix for your application
		applicationId : '38a0a550-b018-4a10-b879-aec68868c249'
	};

var credentials = require('./credentials');

app.use(favicon(__dirname + '/public/favicon.ico'));

var cloudant = require('cloudant')(credentials.cloudant_access_url);
var db = cloudant.use("sauces");

// init core sdk
ibmbluemix.initialize(config);
var logger = ibmbluemix.getLogger();

//redirect to cloudcode doc page when accessing the root context
app.get('/', function(req, res){
	res.sendFile(__dirname + '/public/index.html');
});

// init service sdks 
app.use(function(req, res, next) {
    req.logger = logger;
    next();
});

// init basics for an express app
app.use(require('./lib/setup'));

var ibmconfig = ibmbluemix.getConfig();
console.log(ibmconfig.getContextRoot());
app.get(ibmconfig.getContextRoot()+'/feed',  function(req, res) {
	console.log('Requesting feed');

	db.view("Reviews", "reviews", {descending:true}, function(err, body) {
		if(err) console.log('err '+err);
		else {
			var result = [];
			body.rows.forEach(function(doc) {
				//console.log(doc);
				var item = doc.value;
				item.id = doc.id;
				result.push(item);
			});
			res.setHeader('Content-Type', 'application/json');
			res.json(result);
		}
		
	});
});

app.get(ibmconfig.getContextRoot()+'/sauce/:id',  function(req, res) {
	console.log('Requesting sauce '+req.params.id);
	console.dir(req.params);

	db.get(req.params.id, function(err, body) {
		console.dir(body);
		//TODO: Handle a bad id
		var result = {};
		//for now, just copy it
		result = body;
		res.setHeader('Content-Type', 'application/json');
		res.json(result);		
	});
});


app.use(ibmconfig.getContextRoot(), require('./lib/staticfile'));

// Want to see how you can easily extend this template to work with third party node modules?
// If so, add the Twilio service to your Mobile Cloud application and uncomment this next line.
// app.use(ibmconfig.getContextRoot(), require('./lib/mytwilio')(ibmbluemix));

app.listen(ibmconfig.getPort());
logger.info('Server started at port: '+ibmconfig.getPort());
