var express 	= require('express'),
	app     	= express(),
	favicon 	= require('serve-favicon'),
	ibmbluemix 	= require('ibmbluemix'),
	config  	= {
		// change to real application route assigned for your application
		applicationRoute : 'saucedb.mybluemix.net',
		// change to real application ID generated by Bluemix for your application
		applicationId : '38a0a550-b018-4a10-b879-aec68868c249'
	};

app.use(favicon(__dirname + '/public/favicon.ico'));

var cloudant = require('cloudant')('https://a52742da-6eb5-436f-8d56-bed1885043cf-bluemix:9d8f731f10f36216ad94eab2b2f9296eb03bdf760de03989e306d06e48c335f0@a52742da-6eb5-436f-8d56-bed1885043cf-bluemix.cloudant.com');
var db = cloudant.use("todos");

// init core sdk
ibmbluemix.initialize(config);
var logger = ibmbluemix.getLogger();

//redirect to cloudcode doc page when accessing the root context
app.get('/', function(req, res){
	res.sendFile(__dirname + '/public/index.html');
});

// init service sdks 
app.use(function(req, res, next) {
    req.logger = logger;
    next();
});

// init basics for an express app
app.use(require('./lib/setup'));

var ibmconfig = ibmbluemix.getConfig();

/*
app.get(ibmconfig.getContextRoot()+'/allfree', function(req, res) {
	console.log('FREE1 22got here at least...');
	db.list(function(err, body) {
		if(err) console.log('err '+err);
		else {
			body.rows.forEach(function(doc) {
				console.log(doc);
			});
			res.send('allfree SHORT form, '+body.rows.length);
		}
	});
});
*/

//Everything after here must be an authenticated call
var mas = require('ibmsecurity')();
app.use(mas);

app.get(ibmconfig.getContextRoot()+'/all', function(req, res) {
	console.log('NOT FREEEEE\n\n');
	db.list(function(err, body) {
		if(err) console.log('err '+err);
		else {
			body.rows.forEach(function(doc) {
				console.log(doc);
			});
			res.send('hello from all');
		}
	});
});

app.use(ibmconfig.getContextRoot(), require('./lib/staticfile'));

// Want to see how you can easily extend this template to work with third party node modules?
// If so, add the Twilio service to your Mobile Cloud application and uncomment this next line.
// app.use(ibmconfig.getContextRoot(), require('./lib/mytwilio')(ibmbluemix));

app.listen(ibmconfig.getPort());
logger.info('Server started at port: '+ibmconfig.getPort());
